/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Selection.Sort;

public class App {

    public static void main(String[] args) {

        int [] arr = {8,4,23,42,16,15};
        selectionSort(arr);
        print(arr);
    }

    public static void selectionSort(int[] arr){

        int length = arr.length;

        if(length > 0){
            for(int i = 0; i < length - 1; i++){
                int min = i;
                for(int j = i + 1; j < length; j++){
                    if (arr[j] < arr[min]){
                        min = j;
                    }

                    int temp = arr[min];
                    arr[min] = arr[i];
                    arr[i] = temp;
                }
            }
        }else {
            System.out.println("Array is Empty!");
        }

    }

    public static void print(int[] arr){
        String result = "";
        for(Integer e: arr){
            result = result + e + ", ";
        }

        System.out.println(result);
    }
}
