/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data.structures.and.algorithms;

public class App {

    static final LinkedList<Integer> list = new LinkedList<>();

    public static void main(String[] args) {



        list.insert(5);
        list.insert(10);
//        list.insert(20);
//        list.insert(25);
        list.ChangeValueAtPosition(6, 50);
        System.out.println(list.isIncluded(50));
        System.out.println(list);
//        list.size();
    }

}
