/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Selection.Sort;

import org.junit.Test;
import static org.junit.Assert.*;

public class InsertionSortTest {
    @Test public void appHasAGreeting() {
        InsertionSort classUnderTest = new InsertionSort();
    }
}
