/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Merge.Sort;

import java.util.Arrays;

public class MergeSort {

    public static void main(String[] args) {
        int [] sample = {2,3,5,7,13,11};
        System.out.println(Arrays.toString(mergeSort(sample)));
    }

    public static int[] mergeSort(int [] arr){
        int length = arr.length;

        if(length > 1){
            int mid = length / 2;
            int[] left = Arrays.copyOfRange(arr, 0, mid);
            int[] right = Arrays.copyOfRange(arr, mid, arr.length);
            mergeSort(left);
            mergeSort(right);
            merge(left, right, arr);
        }
        return arr;
    }


    private static void merge(int [] left, int [] right, int [] arr){
        int leftIndex = 0;
        int rightIndex = 0;
        int originalIndex = 0;

        while (leftIndex < left.length && rightIndex < right.length) {

            if (left[leftIndex] <= (right[rightIndex])) {
                arr[originalIndex] = left[leftIndex];
                leftIndex++;
            } else {
                arr[originalIndex] = right[rightIndex];
                rightIndex++;
            }

            originalIndex++;
        }

        if (leftIndex == left.length) {

            while (rightIndex < right.length) {
                arr[originalIndex] = right[rightIndex];
                originalIndex++;
                rightIndex++;
            }

        } else {
            while (leftIndex < left.length) {
                arr[originalIndex] = left[leftIndex];
                originalIndex++;
                leftIndex++;
            }
        }

    }
}
