/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data.structures.and.algorithms;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    private LinkedList<Integer> testList;

    @Test
    public void testInsert(){
        testList = new LinkedList<>();
        testList.insert(5);
        assertEquals("{5} -> Null", testList.toString());
    }

    @Test
    public void testIsIncludedFalse(){
        testList = new LinkedList<>();
        testList.insert(5);
        assertEquals(false, testList.isIncluded(50));
    }

    @Test
    public void testIsIncludedTrue(){
        testList = new LinkedList<>();
        testList.insert(5);
        testList.insert(6);
        assertEquals(true, testList.isIncluded(6));
    }

    @Test
    public void testToString(){
        testList = new LinkedList<>();
        testList.insert(5);
        testList.insert(6);
        assertEquals("{5} -> {6} -> Null", testList.toString());
    }

    @Test
    public void testChangeValueAtPosition(){
        testList = new LinkedList<>();
        testList.insert(5);
        testList.insert(6);
        testList.insert(9);
        testList.ChangeValueAtPosition(2, 2);
        assertEquals("{5} -> {2} -> {9} -> Null", testList.toString());
    }

    @Test
    public void testChangeValueAtPositionFalse(){
        testList = new LinkedList<>();
        testList.insert(5);
        testList.insert(6);
        testList.insert(9);
        testList.ChangeValueAtPosition(60, 2);
        assertEquals("{5} -> {6} -> {9} -> Null", testList.toString());
    }

    @Test
    public void testSize(){
        testList = new LinkedList<>();
        testList.insert(5);
        testList.insert(6);
        testList.insert(9);
        assertEquals(3, testList.size);
    }
}
