/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import HashTable.HashTable;

public class App {

    public static void main(String[] args) {
        HashTable<Integer> map = new HashTable<Integer>();
        map.add("Sufian", 1);
        map.add("Abo_Mattar", 2);
        map.add("Saed", 3);
        System.out.println(map.getSize());
        System.out.println(map.get("Sufian"));
        System.out.println(map.remove("Sufian"));
        System.out.println(map.getSize());
        System.out.println(map.get("Sufian"));
        System.out.println(map.get("Abo_Mattar"));
        System.out.println(map.get("Saed"));
    }
}
